version: '3'

tasks:
  task-1:
    - g++ -Wall common.cc 1/main.cc
    - cat ../input.txt | ./a.exe
    - rm a.exe

  task-2:
    - g++ -Wall common.cc 2/main.cc
    - cat ../input.txt | ./a.exe
    - rm a.exe

  lines:
    - wc -l common* 1/* 2/*
